// GENERATED by scripts/gen_mixed_mma_ptx.py -- do not edit. Regenerate with:
//   python3 scripts/gen_mixed_mma_ptx.py --a-atoms 1 --b-atoms 1 \
//       --m-per-group 2 --n-per-group 2
//
// One k_block of mixed-format MMAs (2x8 atoms = 16 MMAs)
// as 4 inline-PTX statement(s). Each covers a 2x2-atom group and opens
// with its own 16-target brx.idx over just that group's 4 format flags, followed
// by straight-line mma.sync with every format fixed at assembly time.
//
// Granule: 16 rows of A x 8 columns of B x 64 K.
//   (16 rows / 8 columns / 64 K is the hardware floor -- the atom is m16n8k64.)
//
// Dispatch cost: 4 indirect branch(es) per k_block. Each one inside the k_tile body
// costs ~90 cycles, because it stops ptxas interleaving the next k_block's LDSM loads with this
// k_block's MMAs -- see the generator docstring. Code: 64 mma.sync per statement,
// 1024 in the kernel.
#pragma once

#include "cute/tensor.hpp"

#define MIXFP4_GEN_MMA_M        2
#define MIXFP4_GEN_MMA_N        8
#define MIXFP4_GEN_A_ATOMS      1
#define MIXFP4_GEN_B_ATOMS      1
#define MIXFP4_GEN_M_PER_GROUP  2
#define MIXFP4_GEN_N_PER_GROUP  2
#define MIXFP4_GEN_GROUPS       4
#define MIXFP4_GEN_K_GRANULE    64
#define MIXFP4_GEN_OMMAS_PER_KBLOCK 256

namespace mixfp4 {

// acc: (MMA,MMA_M,MMA_N) accumulator fragment.  a: (V,MMA_M) uint32.  b: (V,MMA_N) uint32.
// sfa: (1,MMA_M) uint32.  sfb: (1,MMA_N) uint32.  All indices are compile-time constants.
template <class TAcc, class TA, class TB, class TSFA, class TSFB>
CUTLASS_DEVICE void
mma_kblock(TAcc& acc, TA const& a, TB const& b, TSFA const& sfa, TSFB const& sfb) {
  uint32_t ix[4];
  ix[0] = (((sfa(cute::Int<0>{}, cute::Int<0>{}) >> 7) & 1u) << 0) | (((sfa(cute::Int<0>{}, cute::Int<1>{}) >> 7) & 1u) << 1) | (((sfb(cute::Int<0>{}, cute::Int<0>{}) >> 7) & 1u) << 2) | (((sfb(cute::Int<0>{}, cute::Int<1>{}) >> 7) & 1u) << 3);
  ix[1] = (((sfa(cute::Int<0>{}, cute::Int<0>{}) >> 7) & 1u) << 0) | (((sfa(cute::Int<0>{}, cute::Int<1>{}) >> 7) & 1u) << 1) | (((sfb(cute::Int<0>{}, cute::Int<2>{}) >> 7) & 1u) << 2) | (((sfb(cute::Int<0>{}, cute::Int<3>{}) >> 7) & 1u) << 3);
  ix[2] = (((sfa(cute::Int<0>{}, cute::Int<0>{}) >> 7) & 1u) << 0) | (((sfa(cute::Int<0>{}, cute::Int<1>{}) >> 7) & 1u) << 1) | (((sfb(cute::Int<0>{}, cute::Int<4>{}) >> 7) & 1u) << 2) | (((sfb(cute::Int<0>{}, cute::Int<5>{}) >> 7) & 1u) << 3);
  ix[3] = (((sfa(cute::Int<0>{}, cute::Int<0>{}) >> 7) & 1u) << 0) | (((sfa(cute::Int<0>{}, cute::Int<1>{}) >> 7) & 1u) << 1) | (((sfb(cute::Int<0>{}, cute::Int<6>{}) >> 7) & 1u) << 2) | (((sfb(cute::Int<0>{}, cute::Int<7>{}) >> 7) & 1u) << 3);

  asm volatile(
      "{\n"
      "  .reg .b32 %sf<4>;\n"
      "  G0_TGT: .branchtargets G0_P0, G0_P1, G0_P2, G0_P3, G0_P4, G0_P5, G0_P6, G0_P7, G0_P8, G0_P9, G0_P10, G0_P11, G0_P12, G0_P13, G0_P14, G0_P15;\n"
      "  brx.idx.uni %32, G0_TGT;\n"
      "  G0_P0:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G0_DONE;\n"
      "  G0_P1:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G0_DONE;\n"
      "  G0_P2:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G0_DONE;\n"
      "  G0_P3:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G0_DONE;\n"
      "  G0_P4:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G0_DONE;\n"
      "  G0_P5:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G0_DONE;\n"
      "  G0_P6:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G0_DONE;\n"
      "  G0_P7:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G0_DONE;\n"
      "  G0_P8:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G0_DONE;\n"
      "  G0_P9:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G0_DONE;\n"
      "  G0_P10:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G0_DONE;\n"
      "  G0_P11:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G0_DONE;\n"
      "  G0_P12:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G0_DONE;\n"
      "  G0_P13:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G0_DONE;\n"
      "  G0_P14:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G0_DONE;\n"
      "  G0_P15:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "  G0_DONE:\n"
      "}\n"
      :
        "+f"(acc(cute::Int<0>{}, cute::Int<0>{}, cute::Int<0>{})),
        "+f"(acc(cute::Int<1>{}, cute::Int<0>{}, cute::Int<0>{})),
        "+f"(acc(cute::Int<2>{}, cute::Int<0>{}, cute::Int<0>{})),
        "+f"(acc(cute::Int<3>{}, cute::Int<0>{}, cute::Int<0>{})),
        "+f"(acc(cute::Int<0>{}, cute::Int<0>{}, cute::Int<1>{})),
        "+f"(acc(cute::Int<1>{}, cute::Int<0>{}, cute::Int<1>{})),
        "+f"(acc(cute::Int<2>{}, cute::Int<0>{}, cute::Int<1>{})),
        "+f"(acc(cute::Int<3>{}, cute::Int<0>{}, cute::Int<1>{})),
        "+f"(acc(cute::Int<0>{}, cute::Int<1>{}, cute::Int<0>{})),
        "+f"(acc(cute::Int<1>{}, cute::Int<1>{}, cute::Int<0>{})),
        "+f"(acc(cute::Int<2>{}, cute::Int<1>{}, cute::Int<0>{})),
        "+f"(acc(cute::Int<3>{}, cute::Int<1>{}, cute::Int<0>{})),
        "+f"(acc(cute::Int<0>{}, cute::Int<1>{}, cute::Int<1>{})),
        "+f"(acc(cute::Int<1>{}, cute::Int<1>{}, cute::Int<1>{})),
        "+f"(acc(cute::Int<2>{}, cute::Int<1>{}, cute::Int<1>{})),
        "+f"(acc(cute::Int<3>{}, cute::Int<1>{}, cute::Int<1>{}))
      :
        "r"(a(cute::Int<0>{}, cute::Int<0>{})),
        "r"(a(cute::Int<1>{}, cute::Int<0>{})),
        "r"(a(cute::Int<2>{}, cute::Int<0>{})),
        "r"(a(cute::Int<3>{}, cute::Int<0>{})),
        "r"(a(cute::Int<0>{}, cute::Int<1>{})),
        "r"(a(cute::Int<1>{}, cute::Int<1>{})),
        "r"(a(cute::Int<2>{}, cute::Int<1>{})),
        "r"(a(cute::Int<3>{}, cute::Int<1>{})),
        "r"(b(cute::Int<0>{}, cute::Int<0>{})),
        "r"(b(cute::Int<1>{}, cute::Int<0>{})),
        "r"(b(cute::Int<0>{}, cute::Int<1>{})),
        "r"(b(cute::Int<1>{}, cute::Int<1>{})),
        "r"(sfa(cute::Int<0>{}, cute::Int<0>{})),
        "r"(sfa(cute::Int<0>{}, cute::Int<1>{})),
        "r"(sfb(cute::Int<0>{}, cute::Int<0>{})),
        "r"(sfb(cute::Int<0>{}, cute::Int<1>{})),
        "r"(ix[0]));

  asm volatile(
      "{\n"
      "  .reg .b32 %sf<4>;\n"
      "  G1_TGT: .branchtargets G1_P0, G1_P1, G1_P2, G1_P3, G1_P4, G1_P5, G1_P6, G1_P7, G1_P8, G1_P9, G1_P10, G1_P11, G1_P12, G1_P13, G1_P14, G1_P15;\n"
      "  brx.idx.uni %32, G1_TGT;\n"
      "  G1_P0:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G1_DONE;\n"
      "  G1_P1:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G1_DONE;\n"
      "  G1_P2:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G1_DONE;\n"
      "  G1_P3:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G1_DONE;\n"
      "  G1_P4:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G1_DONE;\n"
      "  G1_P5:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G1_DONE;\n"
      "  G1_P6:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G1_DONE;\n"
      "  G1_P7:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G1_DONE;\n"
      "  G1_P8:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G1_DONE;\n"
      "  G1_P9:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G1_DONE;\n"
      "  G1_P10:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G1_DONE;\n"
      "  G1_P11:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G1_DONE;\n"
      "  G1_P12:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G1_DONE;\n"
      "  G1_P13:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G1_DONE;\n"
      "  G1_P14:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G1_DONE;\n"
      "  G1_P15:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "  G1_DONE:\n"
      "}\n"
      :
        "+f"(acc(cute::Int<0>{}, cute::Int<0>{}, cute::Int<2>{})),
        "+f"(acc(cute::Int<1>{}, cute::Int<0>{}, cute::Int<2>{})),
        "+f"(acc(cute::Int<2>{}, cute::Int<0>{}, cute::Int<2>{})),
        "+f"(acc(cute::Int<3>{}, cute::Int<0>{}, cute::Int<2>{})),
        "+f"(acc(cute::Int<0>{}, cute::Int<0>{}, cute::Int<3>{})),
        "+f"(acc(cute::Int<1>{}, cute::Int<0>{}, cute::Int<3>{})),
        "+f"(acc(cute::Int<2>{}, cute::Int<0>{}, cute::Int<3>{})),
        "+f"(acc(cute::Int<3>{}, cute::Int<0>{}, cute::Int<3>{})),
        "+f"(acc(cute::Int<0>{}, cute::Int<1>{}, cute::Int<2>{})),
        "+f"(acc(cute::Int<1>{}, cute::Int<1>{}, cute::Int<2>{})),
        "+f"(acc(cute::Int<2>{}, cute::Int<1>{}, cute::Int<2>{})),
        "+f"(acc(cute::Int<3>{}, cute::Int<1>{}, cute::Int<2>{})),
        "+f"(acc(cute::Int<0>{}, cute::Int<1>{}, cute::Int<3>{})),
        "+f"(acc(cute::Int<1>{}, cute::Int<1>{}, cute::Int<3>{})),
        "+f"(acc(cute::Int<2>{}, cute::Int<1>{}, cute::Int<3>{})),
        "+f"(acc(cute::Int<3>{}, cute::Int<1>{}, cute::Int<3>{}))
      :
        "r"(a(cute::Int<0>{}, cute::Int<0>{})),
        "r"(a(cute::Int<1>{}, cute::Int<0>{})),
        "r"(a(cute::Int<2>{}, cute::Int<0>{})),
        "r"(a(cute::Int<3>{}, cute::Int<0>{})),
        "r"(a(cute::Int<0>{}, cute::Int<1>{})),
        "r"(a(cute::Int<1>{}, cute::Int<1>{})),
        "r"(a(cute::Int<2>{}, cute::Int<1>{})),
        "r"(a(cute::Int<3>{}, cute::Int<1>{})),
        "r"(b(cute::Int<0>{}, cute::Int<2>{})),
        "r"(b(cute::Int<1>{}, cute::Int<2>{})),
        "r"(b(cute::Int<0>{}, cute::Int<3>{})),
        "r"(b(cute::Int<1>{}, cute::Int<3>{})),
        "r"(sfa(cute::Int<0>{}, cute::Int<0>{})),
        "r"(sfa(cute::Int<0>{}, cute::Int<1>{})),
        "r"(sfb(cute::Int<0>{}, cute::Int<2>{})),
        "r"(sfb(cute::Int<0>{}, cute::Int<3>{})),
        "r"(ix[1]));

  asm volatile(
      "{\n"
      "  .reg .b32 %sf<4>;\n"
      "  G2_TGT: .branchtargets G2_P0, G2_P1, G2_P2, G2_P3, G2_P4, G2_P5, G2_P6, G2_P7, G2_P8, G2_P9, G2_P10, G2_P11, G2_P12, G2_P13, G2_P14, G2_P15;\n"
      "  brx.idx.uni %32, G2_TGT;\n"
      "  G2_P0:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G2_DONE;\n"
      "  G2_P1:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G2_DONE;\n"
      "  G2_P2:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G2_DONE;\n"
      "  G2_P3:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G2_DONE;\n"
      "  G2_P4:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G2_DONE;\n"
      "  G2_P5:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G2_DONE;\n"
      "  G2_P6:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G2_DONE;\n"
      "  G2_P7:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G2_DONE;\n"
      "  G2_P8:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G2_DONE;\n"
      "  G2_P9:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G2_DONE;\n"
      "  G2_P10:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G2_DONE;\n"
      "  G2_P11:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G2_DONE;\n"
      "  G2_P12:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G2_DONE;\n"
      "  G2_P13:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G2_DONE;\n"
      "  G2_P14:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G2_DONE;\n"
      "  G2_P15:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "  G2_DONE:\n"
      "}\n"
      :
        "+f"(acc(cute::Int<0>{}, cute::Int<0>{}, cute::Int<4>{})),
        "+f"(acc(cute::Int<1>{}, cute::Int<0>{}, cute::Int<4>{})),
        "+f"(acc(cute::Int<2>{}, cute::Int<0>{}, cute::Int<4>{})),
        "+f"(acc(cute::Int<3>{}, cute::Int<0>{}, cute::Int<4>{})),
        "+f"(acc(cute::Int<0>{}, cute::Int<0>{}, cute::Int<5>{})),
        "+f"(acc(cute::Int<1>{}, cute::Int<0>{}, cute::Int<5>{})),
        "+f"(acc(cute::Int<2>{}, cute::Int<0>{}, cute::Int<5>{})),
        "+f"(acc(cute::Int<3>{}, cute::Int<0>{}, cute::Int<5>{})),
        "+f"(acc(cute::Int<0>{}, cute::Int<1>{}, cute::Int<4>{})),
        "+f"(acc(cute::Int<1>{}, cute::Int<1>{}, cute::Int<4>{})),
        "+f"(acc(cute::Int<2>{}, cute::Int<1>{}, cute::Int<4>{})),
        "+f"(acc(cute::Int<3>{}, cute::Int<1>{}, cute::Int<4>{})),
        "+f"(acc(cute::Int<0>{}, cute::Int<1>{}, cute::Int<5>{})),
        "+f"(acc(cute::Int<1>{}, cute::Int<1>{}, cute::Int<5>{})),
        "+f"(acc(cute::Int<2>{}, cute::Int<1>{}, cute::Int<5>{})),
        "+f"(acc(cute::Int<3>{}, cute::Int<1>{}, cute::Int<5>{}))
      :
        "r"(a(cute::Int<0>{}, cute::Int<0>{})),
        "r"(a(cute::Int<1>{}, cute::Int<0>{})),
        "r"(a(cute::Int<2>{}, cute::Int<0>{})),
        "r"(a(cute::Int<3>{}, cute::Int<0>{})),
        "r"(a(cute::Int<0>{}, cute::Int<1>{})),
        "r"(a(cute::Int<1>{}, cute::Int<1>{})),
        "r"(a(cute::Int<2>{}, cute::Int<1>{})),
        "r"(a(cute::Int<3>{}, cute::Int<1>{})),
        "r"(b(cute::Int<0>{}, cute::Int<4>{})),
        "r"(b(cute::Int<1>{}, cute::Int<4>{})),
        "r"(b(cute::Int<0>{}, cute::Int<5>{})),
        "r"(b(cute::Int<1>{}, cute::Int<5>{})),
        "r"(sfa(cute::Int<0>{}, cute::Int<0>{})),
        "r"(sfa(cute::Int<0>{}, cute::Int<1>{})),
        "r"(sfb(cute::Int<0>{}, cute::Int<4>{})),
        "r"(sfb(cute::Int<0>{}, cute::Int<5>{})),
        "r"(ix[2]));

  asm volatile(
      "{\n"
      "  .reg .b32 %sf<4>;\n"
      "  G3_TGT: .branchtargets G3_P0, G3_P1, G3_P2, G3_P3, G3_P4, G3_P5, G3_P6, G3_P7, G3_P8, G3_P9, G3_P10, G3_P11, G3_P12, G3_P13, G3_P14, G3_P15;\n"
      "  brx.idx.uni %32, G3_TGT;\n"
      "  G3_P0:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G3_DONE;\n"
      "  G3_P1:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G3_DONE;\n"
      "  G3_P2:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G3_DONE;\n"
      "  G3_P3:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G3_DONE;\n"
      "  G3_P4:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G3_DONE;\n"
      "  G3_P5:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G3_DONE;\n"
      "  G3_P6:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G3_DONE;\n"
      "  G3_P7:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G3_DONE;\n"
      "  G3_P8:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G3_DONE;\n"
      "  G3_P9:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G3_DONE;\n"
      "  G3_P10:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G3_DONE;\n"
      "  G3_P11:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G3_DONE;\n"
      "  G3_P12:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G3_DONE;\n"
      "  G3_P13:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G3_DONE;\n"
      "  G3_P14:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G3_DONE;\n"
      "  G3_P15:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "  G3_DONE:\n"
      "}\n"
      :
        "+f"(acc(cute::Int<0>{}, cute::Int<0>{}, cute::Int<6>{})),
        "+f"(acc(cute::Int<1>{}, cute::Int<0>{}, cute::Int<6>{})),
        "+f"(acc(cute::Int<2>{}, cute::Int<0>{}, cute::Int<6>{})),
        "+f"(acc(cute::Int<3>{}, cute::Int<0>{}, cute::Int<6>{})),
        "+f"(acc(cute::Int<0>{}, cute::Int<0>{}, cute::Int<7>{})),
        "+f"(acc(cute::Int<1>{}, cute::Int<0>{}, cute::Int<7>{})),
        "+f"(acc(cute::Int<2>{}, cute::Int<0>{}, cute::Int<7>{})),
        "+f"(acc(cute::Int<3>{}, cute::Int<0>{}, cute::Int<7>{})),
        "+f"(acc(cute::Int<0>{}, cute::Int<1>{}, cute::Int<6>{})),
        "+f"(acc(cute::Int<1>{}, cute::Int<1>{}, cute::Int<6>{})),
        "+f"(acc(cute::Int<2>{}, cute::Int<1>{}, cute::Int<6>{})),
        "+f"(acc(cute::Int<3>{}, cute::Int<1>{}, cute::Int<6>{})),
        "+f"(acc(cute::Int<0>{}, cute::Int<1>{}, cute::Int<7>{})),
        "+f"(acc(cute::Int<1>{}, cute::Int<1>{}, cute::Int<7>{})),
        "+f"(acc(cute::Int<2>{}, cute::Int<1>{}, cute::Int<7>{})),
        "+f"(acc(cute::Int<3>{}, cute::Int<1>{}, cute::Int<7>{}))
      :
        "r"(a(cute::Int<0>{}, cute::Int<0>{})),
        "r"(a(cute::Int<1>{}, cute::Int<0>{})),
        "r"(a(cute::Int<2>{}, cute::Int<0>{})),
        "r"(a(cute::Int<3>{}, cute::Int<0>{})),
        "r"(a(cute::Int<0>{}, cute::Int<1>{})),
        "r"(a(cute::Int<1>{}, cute::Int<1>{})),
        "r"(a(cute::Int<2>{}, cute::Int<1>{})),
        "r"(a(cute::Int<3>{}, cute::Int<1>{})),
        "r"(b(cute::Int<0>{}, cute::Int<6>{})),
        "r"(b(cute::Int<1>{}, cute::Int<6>{})),
        "r"(b(cute::Int<0>{}, cute::Int<7>{})),
        "r"(b(cute::Int<1>{}, cute::Int<7>{})),
        "r"(sfa(cute::Int<0>{}, cute::Int<0>{})),
        "r"(sfa(cute::Int<0>{}, cute::Int<1>{})),
        "r"(sfb(cute::Int<0>{}, cute::Int<6>{})),
        "r"(sfb(cute::Int<0>{}, cute::Int<7>{})),
        "r"(ix[3]));
}

} // namespace mixfp4
