// GENERATED by scripts/gen_mixed_mma_ptx.py -- do not edit. Regenerate with:
//   python3 scripts/gen_mixed_mma_ptx.py --a-atoms 1 --b-atoms 2 \
//       --m-per-group 2 --n-per-group 2
//
// One k_block of mixed-format MMAs (2x8 atoms = 16 MMAs)
// as 4 inline-PTX statement(s). Each covers a 2x2-atom group and opens
// with its own 8-target brx.idx over just that group's 3 format flags, followed
// by straight-line mma.sync with every format fixed at assembly time.
//
// Granule: 16 rows of A x 16 columns of B x 64 K.
//   (16 rows / 8 columns / 64 K is the hardware floor -- the atom is m16n8k64.)
//
// Dispatch cost: 4 indirect branch(es) per k_block. Each one inside the k_tile body
// costs ~90 cycles, because it stops ptxas interleaving the next k_block's LDSM loads with this
// k_block's MMAs -- see the generator docstring. Code: 32 mma.sync per statement,
// 512 in the kernel.
#pragma once

#include "cute/tensor.hpp"

#define MIXFP4_GEN_MMA_M        2
#define MIXFP4_GEN_MMA_N        8
#define MIXFP4_GEN_A_ATOMS      1
#define MIXFP4_GEN_B_ATOMS      2
#define MIXFP4_GEN_M_PER_GROUP  2
#define MIXFP4_GEN_N_PER_GROUP  2
#define MIXFP4_GEN_GROUPS       4
#define MIXFP4_GEN_K_GRANULE    64
#define MIXFP4_GEN_OMMAS_PER_KBLOCK 128

namespace mixfp4 {

// The jump index, split out so the caller can compute it a k_block EARLY.
//
// It reads only the scale-factor fragments, which copy_kblock() has already loaded for k_block+1
// by the time k_block's MMAs run. Computing it there puts the whole extract/pack chain, and the
// IMAD -> LDC -> BRX that consumes it, off the critical path into the branch. See
// MIXFP4_PIPE_IX in the mainloop.
template <class TSFA, class TSFB>
CUTLASS_DEVICE void
mma_index(TSFA const& sfa, TSFB const& sfb, uint32_t (&ix)[4]) {
#if defined(MIXFP4_FAKE_INDEX) && MIXFP4_FAKE_INDEX
  ix[0] = blockIdx.x & 7u;
  ix[1] = blockIdx.x & 7u;
  ix[2] = blockIdx.x & 7u;
  ix[3] = blockIdx.x & 7u;
#elif defined(MIXFP4_PRMT_INDEX) && MIXFP4_PRMT_INDEX
  ix[0] = (((((__byte_perm(__byte_perm(sfa(cute::Int<0>{}, cute::Int<0>{}), sfa(cute::Int<0>{}, cute::Int<1>{}), 0x0040), sfb(cute::Int<0>{}, cute::Int<0>{}), 0x4010)) & 0x00808080u) >> 7) * 0x00010204u >> 16) & 0x7u);
  ix[1] = (((((__byte_perm(__byte_perm(sfa(cute::Int<0>{}, cute::Int<0>{}), sfa(cute::Int<0>{}, cute::Int<1>{}), 0x0040), sfb(cute::Int<0>{}, cute::Int<2>{}), 0x4010)) & 0x00808080u) >> 7) * 0x00010204u >> 16) & 0x7u);
  ix[2] = (((((__byte_perm(__byte_perm(sfa(cute::Int<0>{}, cute::Int<0>{}), sfa(cute::Int<0>{}, cute::Int<1>{}), 0x0040), sfb(cute::Int<0>{}, cute::Int<4>{}), 0x4010)) & 0x00808080u) >> 7) * 0x00010204u >> 16) & 0x7u);
  ix[3] = (((((__byte_perm(__byte_perm(sfa(cute::Int<0>{}, cute::Int<0>{}), sfa(cute::Int<0>{}, cute::Int<1>{}), 0x0040), sfb(cute::Int<0>{}, cute::Int<6>{}), 0x4010)) & 0x00808080u) >> 7) * 0x00010204u >> 16) & 0x7u);
#else
  ix[0] = (((sfa(cute::Int<0>{}, cute::Int<0>{}) >> 7) & 1u) << 0) | (((sfa(cute::Int<0>{}, cute::Int<1>{}) >> 7) & 1u) << 1) | (((sfb(cute::Int<0>{}, cute::Int<0>{}) >> 7) & 1u) << 2);
  ix[1] = (((sfa(cute::Int<0>{}, cute::Int<0>{}) >> 7) & 1u) << 0) | (((sfa(cute::Int<0>{}, cute::Int<1>{}) >> 7) & 1u) << 1) | (((sfb(cute::Int<0>{}, cute::Int<2>{}) >> 7) & 1u) << 2);
  ix[2] = (((sfa(cute::Int<0>{}, cute::Int<0>{}) >> 7) & 1u) << 0) | (((sfa(cute::Int<0>{}, cute::Int<1>{}) >> 7) & 1u) << 1) | (((sfb(cute::Int<0>{}, cute::Int<4>{}) >> 7) & 1u) << 2);
  ix[3] = (((sfa(cute::Int<0>{}, cute::Int<0>{}) >> 7) & 1u) << 0) | (((sfa(cute::Int<0>{}, cute::Int<1>{}) >> 7) & 1u) << 1) | (((sfb(cute::Int<0>{}, cute::Int<6>{}) >> 7) & 1u) << 2);
#endif
}

// acc: (MMA,MMA_M,MMA_N) accumulator fragment.  a: (V,MMA_M) uint32.  b: (V,MMA_N) uint32.
// sfa: (1,MMA_M) uint32.  sfb: (1,MMA_N) uint32.  All indices are compile-time constants.
template <class TAcc, class TA, class TB, class TSFA, class TSFB>
CUTLASS_DEVICE void
mma_kblock_ix(TAcc& acc, TA const& a, TB const& b, TSFA const& sfa, TSFB const& sfb,
              uint32_t const (&ix)[4]) {
  asm volatile(
      "{\n"
      "  .reg .b32 %sf<4>;\n"
      "  G0_TGT: .branchtargets G0_P0, G0_P1, G0_P2, G0_P3, G0_P4, G0_P5, G0_P6, G0_P7;\n"
      "  brx.idx.uni %32, G0_TGT;\n"
      "  G0_P0:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G0_DONE;\n"
      "  G0_P1:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G0_DONE;\n"
      "  G0_P2:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G0_DONE;\n"
      "  G0_P3:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G0_DONE;\n"
      "  G0_P4:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G0_DONE;\n"
      "  G0_P5:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G0_DONE;\n"
      "  G0_P6:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G0_DONE;\n"
      "  G0_P7:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "  G0_DONE:\n"
      "}\n"
      :
        "+f"(acc(cute::Int<0>{}, cute::Int<0>{}, cute::Int<0>{})),
        "+f"(acc(cute::Int<1>{}, cute::Int<0>{}, cute::Int<0>{})),
        "+f"(acc(cute::Int<2>{}, cute::Int<0>{}, cute::Int<0>{})),
        "+f"(acc(cute::Int<3>{}, cute::Int<0>{}, cute::Int<0>{})),
        "+f"(acc(cute::Int<0>{}, cute::Int<0>{}, cute::Int<1>{})),
        "+f"(acc(cute::Int<1>{}, cute::Int<0>{}, cute::Int<1>{})),
        "+f"(acc(cute::Int<2>{}, cute::Int<0>{}, cute::Int<1>{})),
        "+f"(acc(cute::Int<3>{}, cute::Int<0>{}, cute::Int<1>{})),
        "+f"(acc(cute::Int<0>{}, cute::Int<1>{}, cute::Int<0>{})),
        "+f"(acc(cute::Int<1>{}, cute::Int<1>{}, cute::Int<0>{})),
        "+f"(acc(cute::Int<2>{}, cute::Int<1>{}, cute::Int<0>{})),
        "+f"(acc(cute::Int<3>{}, cute::Int<1>{}, cute::Int<0>{})),
        "+f"(acc(cute::Int<0>{}, cute::Int<1>{}, cute::Int<1>{})),
        "+f"(acc(cute::Int<1>{}, cute::Int<1>{}, cute::Int<1>{})),
        "+f"(acc(cute::Int<2>{}, cute::Int<1>{}, cute::Int<1>{})),
        "+f"(acc(cute::Int<3>{}, cute::Int<1>{}, cute::Int<1>{}))
      :
        "r"(a(cute::Int<0>{}, cute::Int<0>{})),
        "r"(a(cute::Int<1>{}, cute::Int<0>{})),
        "r"(a(cute::Int<2>{}, cute::Int<0>{})),
        "r"(a(cute::Int<3>{}, cute::Int<0>{})),
        "r"(a(cute::Int<0>{}, cute::Int<1>{})),
        "r"(a(cute::Int<1>{}, cute::Int<1>{})),
        "r"(a(cute::Int<2>{}, cute::Int<1>{})),
        "r"(a(cute::Int<3>{}, cute::Int<1>{})),
        "r"(b(cute::Int<0>{}, cute::Int<0>{})),
        "r"(b(cute::Int<1>{}, cute::Int<0>{})),
        "r"(b(cute::Int<0>{}, cute::Int<1>{})),
        "r"(b(cute::Int<1>{}, cute::Int<1>{})),
        "r"(sfa(cute::Int<0>{}, cute::Int<0>{})),
        "r"(sfa(cute::Int<0>{}, cute::Int<1>{})),
        "r"(sfb(cute::Int<0>{}, cute::Int<0>{})),
        "r"(sfb(cute::Int<0>{}, cute::Int<1>{})),
        "r"(ix[0]));

  asm volatile(
      "{\n"
      "  .reg .b32 %sf<4>;\n"
      "  G1_TGT: .branchtargets G1_P0, G1_P1, G1_P2, G1_P3, G1_P4, G1_P5, G1_P6, G1_P7;\n"
      "  brx.idx.uni %32, G1_TGT;\n"
      "  G1_P0:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G1_DONE;\n"
      "  G1_P1:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G1_DONE;\n"
      "  G1_P2:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G1_DONE;\n"
      "  G1_P3:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G1_DONE;\n"
      "  G1_P4:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G1_DONE;\n"
      "  G1_P5:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G1_DONE;\n"
      "  G1_P6:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G1_DONE;\n"
      "  G1_P7:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "  G1_DONE:\n"
      "}\n"
      :
        "+f"(acc(cute::Int<0>{}, cute::Int<0>{}, cute::Int<2>{})),
        "+f"(acc(cute::Int<1>{}, cute::Int<0>{}, cute::Int<2>{})),
        "+f"(acc(cute::Int<2>{}, cute::Int<0>{}, cute::Int<2>{})),
        "+f"(acc(cute::Int<3>{}, cute::Int<0>{}, cute::Int<2>{})),
        "+f"(acc(cute::Int<0>{}, cute::Int<0>{}, cute::Int<3>{})),
        "+f"(acc(cute::Int<1>{}, cute::Int<0>{}, cute::Int<3>{})),
        "+f"(acc(cute::Int<2>{}, cute::Int<0>{}, cute::Int<3>{})),
        "+f"(acc(cute::Int<3>{}, cute::Int<0>{}, cute::Int<3>{})),
        "+f"(acc(cute::Int<0>{}, cute::Int<1>{}, cute::Int<2>{})),
        "+f"(acc(cute::Int<1>{}, cute::Int<1>{}, cute::Int<2>{})),
        "+f"(acc(cute::Int<2>{}, cute::Int<1>{}, cute::Int<2>{})),
        "+f"(acc(cute::Int<3>{}, cute::Int<1>{}, cute::Int<2>{})),
        "+f"(acc(cute::Int<0>{}, cute::Int<1>{}, cute::Int<3>{})),
        "+f"(acc(cute::Int<1>{}, cute::Int<1>{}, cute::Int<3>{})),
        "+f"(acc(cute::Int<2>{}, cute::Int<1>{}, cute::Int<3>{})),
        "+f"(acc(cute::Int<3>{}, cute::Int<1>{}, cute::Int<3>{}))
      :
        "r"(a(cute::Int<0>{}, cute::Int<0>{})),
        "r"(a(cute::Int<1>{}, cute::Int<0>{})),
        "r"(a(cute::Int<2>{}, cute::Int<0>{})),
        "r"(a(cute::Int<3>{}, cute::Int<0>{})),
        "r"(a(cute::Int<0>{}, cute::Int<1>{})),
        "r"(a(cute::Int<1>{}, cute::Int<1>{})),
        "r"(a(cute::Int<2>{}, cute::Int<1>{})),
        "r"(a(cute::Int<3>{}, cute::Int<1>{})),
        "r"(b(cute::Int<0>{}, cute::Int<2>{})),
        "r"(b(cute::Int<1>{}, cute::Int<2>{})),
        "r"(b(cute::Int<0>{}, cute::Int<3>{})),
        "r"(b(cute::Int<1>{}, cute::Int<3>{})),
        "r"(sfa(cute::Int<0>{}, cute::Int<0>{})),
        "r"(sfa(cute::Int<0>{}, cute::Int<1>{})),
        "r"(sfb(cute::Int<0>{}, cute::Int<2>{})),
        "r"(sfb(cute::Int<0>{}, cute::Int<3>{})),
        "r"(ix[1]));

  asm volatile(
      "{\n"
      "  .reg .b32 %sf<4>;\n"
      "  G2_TGT: .branchtargets G2_P0, G2_P1, G2_P2, G2_P3, G2_P4, G2_P5, G2_P6, G2_P7;\n"
      "  brx.idx.uni %32, G2_TGT;\n"
      "  G2_P0:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G2_DONE;\n"
      "  G2_P1:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G2_DONE;\n"
      "  G2_P2:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G2_DONE;\n"
      "  G2_P3:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G2_DONE;\n"
      "  G2_P4:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G2_DONE;\n"
      "  G2_P5:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G2_DONE;\n"
      "  G2_P6:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G2_DONE;\n"
      "  G2_P7:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "  G2_DONE:\n"
      "}\n"
      :
        "+f"(acc(cute::Int<0>{}, cute::Int<0>{}, cute::Int<4>{})),
        "+f"(acc(cute::Int<1>{}, cute::Int<0>{}, cute::Int<4>{})),
        "+f"(acc(cute::Int<2>{}, cute::Int<0>{}, cute::Int<4>{})),
        "+f"(acc(cute::Int<3>{}, cute::Int<0>{}, cute::Int<4>{})),
        "+f"(acc(cute::Int<0>{}, cute::Int<0>{}, cute::Int<5>{})),
        "+f"(acc(cute::Int<1>{}, cute::Int<0>{}, cute::Int<5>{})),
        "+f"(acc(cute::Int<2>{}, cute::Int<0>{}, cute::Int<5>{})),
        "+f"(acc(cute::Int<3>{}, cute::Int<0>{}, cute::Int<5>{})),
        "+f"(acc(cute::Int<0>{}, cute::Int<1>{}, cute::Int<4>{})),
        "+f"(acc(cute::Int<1>{}, cute::Int<1>{}, cute::Int<4>{})),
        "+f"(acc(cute::Int<2>{}, cute::Int<1>{}, cute::Int<4>{})),
        "+f"(acc(cute::Int<3>{}, cute::Int<1>{}, cute::Int<4>{})),
        "+f"(acc(cute::Int<0>{}, cute::Int<1>{}, cute::Int<5>{})),
        "+f"(acc(cute::Int<1>{}, cute::Int<1>{}, cute::Int<5>{})),
        "+f"(acc(cute::Int<2>{}, cute::Int<1>{}, cute::Int<5>{})),
        "+f"(acc(cute::Int<3>{}, cute::Int<1>{}, cute::Int<5>{}))
      :
        "r"(a(cute::Int<0>{}, cute::Int<0>{})),
        "r"(a(cute::Int<1>{}, cute::Int<0>{})),
        "r"(a(cute::Int<2>{}, cute::Int<0>{})),
        "r"(a(cute::Int<3>{}, cute::Int<0>{})),
        "r"(a(cute::Int<0>{}, cute::Int<1>{})),
        "r"(a(cute::Int<1>{}, cute::Int<1>{})),
        "r"(a(cute::Int<2>{}, cute::Int<1>{})),
        "r"(a(cute::Int<3>{}, cute::Int<1>{})),
        "r"(b(cute::Int<0>{}, cute::Int<4>{})),
        "r"(b(cute::Int<1>{}, cute::Int<4>{})),
        "r"(b(cute::Int<0>{}, cute::Int<5>{})),
        "r"(b(cute::Int<1>{}, cute::Int<5>{})),
        "r"(sfa(cute::Int<0>{}, cute::Int<0>{})),
        "r"(sfa(cute::Int<0>{}, cute::Int<1>{})),
        "r"(sfb(cute::Int<0>{}, cute::Int<4>{})),
        "r"(sfb(cute::Int<0>{}, cute::Int<5>{})),
        "r"(ix[2]));

  asm volatile(
      "{\n"
      "  .reg .b32 %sf<4>;\n"
      "  G3_TGT: .branchtargets G3_P0, G3_P1, G3_P2, G3_P3, G3_P4, G3_P5, G3_P6, G3_P7;\n"
      "  brx.idx.uni %32, G3_TGT;\n"
      "  G3_P0:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G3_DONE;\n"
      "  G3_P1:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G3_DONE;\n"
      "  G3_P2:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3210;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G3_DONE;\n"
      "  G3_P3:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3214;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G3_DONE;\n"
      "  G3_P4:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G3_DONE;\n"
      "  G3_P5:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G3_DONE;\n"
      "  G3_P6:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3254;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "    bra.uni G3_DONE;\n"
      "  G3_P7:\n"
      "    prmt.b32 %sf0, %28, %28, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%0,%1,%2,%3}, {%16,%17,%18,%19}, {%24,%25}, {%0,%1,%2,%3}, {%sf0}, {0, 0}, {%30}, {0, 0};\n"
      "    prmt.b32 %sf1, %28, %28, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%4,%5,%6,%7}, {%16,%17,%18,%19}, {%26,%27}, {%4,%5,%6,%7}, {%sf1}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf2, %29, %29, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%12,%13,%14,%15}, {%20,%21,%22,%23}, {%26,%27}, {%12,%13,%14,%15}, {%sf2}, {0, 0}, {%31}, {0, 0};\n"
      "    prmt.b32 %sf3, %29, %29, 0x3654;\n"
      "    mma.sync.aligned.kind::mxf4nvf4.block_scale.scale_vec::4X.m16n8k64.row.col.f32.e2m1.e2m1.f32.ue4m3 {%8,%9,%10,%11}, {%20,%21,%22,%23}, {%24,%25}, {%8,%9,%10,%11}, {%sf3}, {0, 0}, {%30}, {0, 0};\n"
      "  G3_DONE:\n"
      "}\n"
      :
        "+f"(acc(cute::Int<0>{}, cute::Int<0>{}, cute::Int<6>{})),
        "+f"(acc(cute::Int<1>{}, cute::Int<0>{}, cute::Int<6>{})),
        "+f"(acc(cute::Int<2>{}, cute::Int<0>{}, cute::Int<6>{})),
        "+f"(acc(cute::Int<3>{}, cute::Int<0>{}, cute::Int<6>{})),
        "+f"(acc(cute::Int<0>{}, cute::Int<0>{}, cute::Int<7>{})),
        "+f"(acc(cute::Int<1>{}, cute::Int<0>{}, cute::Int<7>{})),
        "+f"(acc(cute::Int<2>{}, cute::Int<0>{}, cute::Int<7>{})),
        "+f"(acc(cute::Int<3>{}, cute::Int<0>{}, cute::Int<7>{})),
        "+f"(acc(cute::Int<0>{}, cute::Int<1>{}, cute::Int<6>{})),
        "+f"(acc(cute::Int<1>{}, cute::Int<1>{}, cute::Int<6>{})),
        "+f"(acc(cute::Int<2>{}, cute::Int<1>{}, cute::Int<6>{})),
        "+f"(acc(cute::Int<3>{}, cute::Int<1>{}, cute::Int<6>{})),
        "+f"(acc(cute::Int<0>{}, cute::Int<1>{}, cute::Int<7>{})),
        "+f"(acc(cute::Int<1>{}, cute::Int<1>{}, cute::Int<7>{})),
        "+f"(acc(cute::Int<2>{}, cute::Int<1>{}, cute::Int<7>{})),
        "+f"(acc(cute::Int<3>{}, cute::Int<1>{}, cute::Int<7>{}))
      :
        "r"(a(cute::Int<0>{}, cute::Int<0>{})),
        "r"(a(cute::Int<1>{}, cute::Int<0>{})),
        "r"(a(cute::Int<2>{}, cute::Int<0>{})),
        "r"(a(cute::Int<3>{}, cute::Int<0>{})),
        "r"(a(cute::Int<0>{}, cute::Int<1>{})),
        "r"(a(cute::Int<1>{}, cute::Int<1>{})),
        "r"(a(cute::Int<2>{}, cute::Int<1>{})),
        "r"(a(cute::Int<3>{}, cute::Int<1>{})),
        "r"(b(cute::Int<0>{}, cute::Int<6>{})),
        "r"(b(cute::Int<1>{}, cute::Int<6>{})),
        "r"(b(cute::Int<0>{}, cute::Int<7>{})),
        "r"(b(cute::Int<1>{}, cute::Int<7>{})),
        "r"(sfa(cute::Int<0>{}, cute::Int<0>{})),
        "r"(sfa(cute::Int<0>{}, cute::Int<1>{})),
        "r"(sfb(cute::Int<0>{}, cute::Int<6>{})),
        "r"(sfb(cute::Int<0>{}, cute::Int<7>{})),
        "r"(ix[3]));
}

template <class TAcc, class TA, class TB, class TSFA, class TSFB>
CUTLASS_DEVICE void
mma_kblock(TAcc& acc, TA const& a, TB const& b, TSFA const& sfa, TSFB const& sfb) {
  uint32_t ix[4];
  mma_index(sfa, sfb, ix);
  mma_kblock_ix(acc, a, b, sfa, sfb, ix);
}

} // namespace mixfp4
